---

- name: Ensure apt packages are present
  apt: name="{{item}}" state=present update_cache=yes cache_valid_time=3600
  with_items:
    - ssh
    - rsync

- name: Template sysctl.conf to ensure ipv6 disabled
  template: src="sysctl.conf" dest="/etc/sysctl.conf" backup=yes