---
- name: Check installed
  stat: 
    path: "{{ druid_home }}/druid-{{ druid.version }}/config"
  register: check_installation

- name: Ensure druid.download.dest exists
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ druid.download.dest }}"
    - "{{ druid_home }}"
  when: check_installation.stat.isdir is defined and check_installation.stat.isdir

- name: Ensure tar downloaded to tar dir druid.download.dest
  get_url:
    url: "http://static.druid.io/artifacts/releases/druid-{{ druid.version }}-bin.tar.gz"
    dest: "{{ druid.download.dest }}"
  when: check_installation.stat.islnk is not defined

- name: Ensure druid tar unarchived to druid_home
  unarchive:
    src: "{{ druid.download.dest }}/druid-{{ druid.version }}-bin.tar.gz"
    dest: "{{ druid_home }}"
    copy: no
  when: check_installation.stat.islnk is not defined