---

- name: Ensure {{ tranquility_dir }} dir exists
  file:
    dest: "{{ item.dest }}"
    state: directory
  with_items:
    - dest: "/opt/src"
    - dest: "{{ tranquility_dir }}"
    - dest: "{{ tranquility_bin_dir }}"
  
- name: Download tranquility to opt/src
  get_url:
    url: "http://static.druid.io/tranquility/releases/tranquility-distribution-{{ tranquility_version }}.tgz"
    dest: "/opt/src/tranquility-distribution-{{ tranquility_version }}.tgz"

- name: Unpack tranquility tarball
  unarchive:
    src: "/opt/src/tranquility-distribution-{{ tranquility_version }}.tgz"
    dest: "{{ tranquility_dir }}"
    remote_src: yes
    copy: no

- name: Template config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - src: python_gen_kafka_metrics.py.j2
      dest: "{{ tranquility_bin_dir }}/python_gen_kafka_metrics.py"
      mode: "0755"
    - src: http.json.j2
      dest: "{{ tranquility_http_server_config_dest }}"
    - src: kafka.json.j2
      dest: "{{ tranquility_kafka_server_config_dest }}"

- name: Template upstart
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  with_items:
    - src: "tranquility_kafka.conf.j2"
      dest: "/etc/init/tranquility_kafka.conf"
    - src: "tranquility_http.conf.j2"
      dest: "/etc/init/tranquility_http.conf"
