kafka_version: "0.9.0.0"
kafka_pkg_url: "http://www.interior-dsgn.com/apache/kafka/{{ kafka_version }}/kafka_2.11-{{ kafka_version }}.tgz"
kafka_dir: "/opt/kafka-{{kafka_version}}"
kafka_conf_dir: "{{kafka_dir}}/config"
kafka_data: "/var/lib/kafka"
kafka_logs: "/var/log/kafka"

# server.properties
kafka_brokers:
  - localhost
kafka_listeners_port: "9092"
# kafka_zk_endpoint should be overridden with comma separated list of zookeeper servers
kafka_zk_endpoint: "localhost:2181"
kafka_host_name: "localhost"