---

core_servers:
  hosts: [ core1.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
zookeeper_servers:
  hosts: [ zookeeper0.lan, zookeeper1.lan, zookeeper2.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
kafka_servers:
  hosts: [ kafka0.lan, kafka1.lan, kafka2.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
hadoop_servers:
  hosts: [ hadoop0.lan, hadoop1.lan, hadoop2.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
druid_servers:
  hosts: [ druid0.lan ]
  vars:
    ansible_ssh_user: vagrant
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
all:
  children: [ core_servers, zookeeper_servers, kafka_servers, hadoop_servers, druid_servers ]
_meta:
  hostvars:
    core1.lan:
      vagrant_ip: "172.16.8.2"
      vagrant_mem: "1024"
    zookeeper0.lan:
      vagrant_ip: "172.16.8.10"
    zookeeper1.lan:
      vagrant_ip: "172.16.8.11"
    zookeeper2.lan:
      vagrant_ip: "172.16.8.12"
    kafka0.lan:
      vagrant_ip: "172.16.8.20"
    kafka1.lan:
      vagrant_ip: "172.16.8.21"
    kafka2.lan:
      vagrant_ip: "172.16.8.22"
    hadoop0.lan:
      vagrant_ip: "172.16.8.30"
    hadoop1.lan:
      vagrant_ip: "172.16.8.31"
    hadoop2.lan:
      vagrant_ip: "172.16.8.32"
    druid0.lan:
      vagrant_ip: "172.16.8.40"
      vagrant_mem: "8096"
      vagrant_cpu: "2"
    druid1.lan:
      vagrant_ip: "172.16.8.41"
    druid2.lan:
      vagrant_ip: "172.16.8.42"
