---

- hosts: druid_servers
  become: yes
  become_user: root
  vars_files:
    - vars/makevault.yml

  roles:
    - role: mysql
      mysql_root_password: "{{ druid_cluster_mysql_root_password }}"
      mysql_databases: "{{ druid_cluster_mysql_databases }}"
      mysql_users: "{{ druid_cluster_mysql_users }}"