---

- hosts: druid_servers
  become: yes
  become_user: root
  vars_files:
    - vars/makevault.yml

  roles:
    - role: druid
      druid_host_services: ["coordinator", "historical", "broker", "middlemanager", "overlord"]
      druid_zk_ips: "zookeeper0.lan:2181,zookeeper1.lan:2181,zookeeper2.lan:2181"
      druid_storage_type: "hdfs"
      druid_storage_storageDirectory: "hdfs://hadoop0.lan:9000/user/druid/segments/"
      druid_metadata_storage_type: "mysql"
      druid_metadata_storage_connector_connectURI: "jdbc:mysql://{{ inventory_hostname }}/druid"
      druid_metadata_storage_connector_user: "{{ druid_cluster_druid_db_user }}"
      druid_metadata_storage_connector_password: "{{ druid_cluster_druid_db_password }}"
      druid_indexer_logs_type: "hdfs"
      druid_indexer_logs_directory: "hdfs://hadoop0.lan:9000/user/druid/indexing-logs/"      
      druid_extensions_loadlist: ["druid-hdfs-storage", "druid-kafka-eight", "druid-s3-extensions", "druid-histogram", "druid-datasketches", "druid-lookups-cached-global", "mysql-metadata-storage"]
