---

- hosts: zookeeper_servers
  become: yes
  become_user: root
  vars_files:
    - vars/makevault.yml

  roles:
    - role: zookeeper
      zookeeper_version: "3.4.5"
      zookeeper_servers: "{{ groups['zookeeper_servers'] }}"